name: Make deploy to server

on:
  push:
    branches:
      - push
  
jobs:
  package_install:
    name: Package install & Build & Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
           node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
            npm ci
        env:
          CI: true

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - package_install
    steps:
      - name: npm run build
        run: |
            npm run deploy --if-present

  upload-artifact:
    name: Upload-artifact
    needs: build
    steps:
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public/

  sync-with-s3:
    name: Sync with AWS S3
    needs: upload-artifact
    steps:
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        run: aws s3 sync public/ ${{ secrets.AWS_S3_BUCKET_NAME }} --delete
