name: Make deploy to server

on:
  push:
    branches:
      - master
  
jobs:
  # パッケージのインストールとビルド
  build:
    name: Package install & Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
           node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
            npm ci
            npm run deploy --if-present
        env:
          CI: true
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public/

  # S3と同期する
  sync-with-s3:
    name: Sync with AWS S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ~/dist/
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        run: aws s3 sync ~/dist/ ${{ secrets.AWS_S3_BUCKET_NAME }} --delete
